argocd:
  namespace: argocd

self:
  name: argocd-apps
  repoUrl: https://github.com/ish10k/find-fuel-argocd-apps
  targetRevision: main
  path: .
  namespace: argocd-apps

ingress:
  name: argocd-ingress
  host: argocd.findfuel.uk
  service: argocd-server

findFuelMain:
  name: find-fuel-main
  repoUrl: https://github.com/ish10k/find-fuel-main-chart
  targetRevision: main
  path: .
  namespace: find-fuel

findFuelCnpgDb:
  name: cnpg-db
  repoUrl: https://github.com/ish10k/find-fuel-cnpg-db-chart
  targetRevision: main
  path: .
  namespace: find-fuel-cnpg-db

cnpgOperator:
  name: cnpg-operator
  repoUrl: https://github.com/cloudnative-pg/charts
  targetRevision: main
  path: charts/cloudnative-pg
  namespace: cnpg
