argocd:
  namespace: argocd

self:
  name: agrocd-apps
  repoUrl: https://github.com/ish10k/find-fuel-argocd-apps
  targetRevision: main
  path: .
  namespace: argocd-apps

findFuelMain:
  name: find-fuel-main
  repoUrl: https://github.com/ish10k/find-fuel-main-chart
  targetRevision: main
  path: .
  namespace: find-fuel

findFuelCnpgDb:
  name: cnpg-db
  repoUrl: https://github.com/ish10k/find-fuel-cnpg-db-chart
  targetRevision: main
  path: .
  namespace: find-fuel-cnpg-db

cnpgOperator:
  name: cnpg-operator
  repoUrl: https://github.com/cloudnative-pg/charts
  targetRevision: main
  path: charts/cloudnative-pg
  namespace: cnpg
