argocd:
  namespace: argocd

self:
  name: argocd-apps
  repoUrl: https://github.com/ish10k/find-fuel-argocd-apps
  targetRevision: main
  path: .
  namespace: argocd-apps

ingress:
  name: argocd-ingress
  host: argocd.findfuel.uk
  service: argocd-server

certIssuer:
  staging:
    name: cert-issuer-staging
    email: inale02@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
  
  prod:
    name: cert-issuer-prod
    email: inale02@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory

certificate:
  name: cert
  certIssuerName: cert-issuer-prod

certManagerOperator:
  name: cert-manager-operator
  repoUrl: https://charts.jetstack.io
  targetRevision: v1.14.4
  chart: cert-manager
  namespace: cert-manager

findFuelMain:
  name: find-fuel-main
  repoUrl: https://github.com/ish10k/find-fuel-main-chart
  targetRevision: main
  path: .
  namespace: find-fuel

findFuelCnpgDb:
  name: cnpg-db
  repoUrl: https://github.com/ish10k/find-fuel-cnpg-db-chart
  targetRevision: main
  path: .
  namespace: find-fuel-cnpg-db

cnpgOperator:
  name: cnpg-operator
  repoUrl: https://github.com/cloudnative-pg/charts
  targetRevision: main
  path: charts/cloudnative-pg
  namespace: cnpg

grafanaStack:
  name: grafana-stack
  repoUrl: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  targetRevision: 70.1.1
  adminPassword: admin
  namespace: o11y
  ingress:
    name: grafana-stack-ingress
    host: grafana.findfuel.uk
    service: grafana-stack

loki:
  name: loki
  namespace: o11y
  chart: loki
  repoUrl: https://grafana.github.io/helm-charts
  targetRevision: 6.28.0
