argocd:
  namespace: argocd

self:
  name: argocd-apps
  repoUrl: https://github.com/ish10k/find-fuel-argocd-apps
  targetRevision: main
  path: .
  namespace: argocd-apps

ingress:
  name: argocd-ingress
  host: argocd.findfuel.uk
  service: argocd-service

findFuelMain:
  name: find-fuel-main
  repoUrl: https://github.com/ish10k/find-fuel-main-chart
  targetRevision: main
  path: .
  namespace: find-fuel

findFuelCnpgDb:
  name: cnpg-db
  repoUrl: https://github.com/ish10k/find-fuel-cnpg-db-chart
  targetRevision: main
  path: .
  namespace: find-fuel-cnpg-db

cnpgOperator:
  name: cnpg-operator
  repoUrl: https://github.com/cloudnative-pg/charts
  targetRevision: main
  path: charts/cloudnative-pg
  namespace: cnpg

grafanaStack:
  name: grafana-stack
  repoUrl: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  targetRevision: main
  adminPassword: admin
  namespace: o11y

lokiStack:
  name: loki-stack
  namespace: o11y
  chart: loki-stack
  repoUrl: https://grafana.github.io/helm-charts
  targetRevision: main
