apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.cert-issuer.staging.name }}
spec:
  acme:
    email: {{ .Values.cert-issuer.staging.email }}
    server: {{ .Values.cert-issuer.staging.server }}
    privateKeySecretRef:
      name: {{ .Values.cert-issuer.staging.name }}
    solvers:
    - http01:
        ingress:
          class: nginx