apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.lokiStack.name }}
  namespace: {{ .Values.argocd.namespace }}
spec:
  project: default
  source:
    chart: {{ .Values.lokiStack.chart }}
    repoURL: {{ .Values.lokiStack.repoUrl }}
    targetRevision: {{ .Values.lokiStack.targetRevision }}
    helm:
      values: |
        loki:
          persistence:
            enabled: true
          image:
            tag: '2.9.3'
        promtail:
          enabled: true
          config:
            clients:
              - url: http://loki.o11y.svc:3100/loki/api/v1/push
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.lokiStack.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=True