apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.loki.name }}
  namespace: {{ .Values.argocd.namespace }}
spec:
  project: default
  source:
    chart: {{ .Values.loki.chart }}
    repoURL: {{ .Values.loki.repoUrl }}
    targetRevision: {{ .Values.loki.targetRevision }}
    helm:
      values: |
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          schemaConfig:
            configs:
            - from: "2024-04-01"
              store: boltdb-shipper
              object_store: filesystem
              schema: v12
              index:
                prefix: loki_index_
                period: 24h
        deploymentMode: SingleBinary
        singleBinary:
          replicas: 1
        write:
          replicas: 0
        read:
          replicas: 0
        backend:
          replicas: 0

        promtail:
          enabled: true
          config:
            clients:
              - url: http://{{ .Values.loki.name }}.{{ .Values.loki.namespace }}.svc:3100/loki/api/v1/push
            snippets:
              pipelineStages:
                - cri: {}
            scrapeConfigs:
              - job_name: kubernetes-pods
                pipeline_stages:
                  - cri: {}
                kubernetes_sd_configs:
                  - role: pod
                relabel_configs:
                  - source_labels: [__meta_kubernetes_pod_label_app]
                    target_label: app
                  - source_labels: [__meta_kubernetes_namespace]
                    target_label: namespace
                  - source_labels: [__meta_kubernetes_pod_name]
                    target_label: pod
                  - source_labels: [__meta_kubernetes_pod_container_name]
                    target_label: container

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.loki.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=True